export const ACTIONS = {
  MENU_ELEMENT_DROP: 'MENU_ELEMENT_DROP',
  MENU_ELEMENT_DRAG: 'MEN_ELEMENT_DRAG',
  MENU_ELEMENT_SELECTED: 'MENU_ELEMENT_SELECTED',
  MENU_ELEMENT_REMOVED: 'MENU_ELEMENT_REMOVED',
  CONTAINER_ELEMENT_SELECTED: 'CONTAINER_ELEMENT_SELECTED',
  CONTAINER_ELEMENT_DROP: 'CONTAINER_ELEMENT_DROP',
  CONTAINER_ELEMENT_DRAG: 'CONTAINER_ELEMENT_DRAG',
  CONTAINER_ELEMENT_DRAG_CANCEL: 'CONTAINER_ELEMENT_DRAG_CANCEL',
  CONTAINER_ELEMENT_REMOVED: 'CONTAINER_ELEMENT_REMOVED',
  CONTAINER_ELEMENT_INIT_NEW_FORM: 'CONTAINER_ELEMENT_INIT_NEW_FORM'
};
